version: "3.8"
services:
  postgres:
    image: postgres:16.0
    container_name: hrm_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lpdev
      POSTGRES_PASSWORD: Abcd1234
      POSTGRES_DB: hrm
    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: unless-stopped
    user: "$UID:$GID"
    ports:
      - "8079:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Abcd1234
    volumes:
      - ./docker/pgadmin-data:/var/lib/pgadmin

  app:
    image: "docker-spring-boot-postgres:latest"
    build:
      context: .
    container_name: app
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/hrm
      - SPRING_DATASOURCE_USERNAME=lpdev
      - SPRING_DATASOURCE_PASSWORD=Abcd1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update