-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
INSERT INTO public.branch (active_status, branch_name, branch_type, capacity, contact_person, location, phone_number)
VALUES
(TRUE, 'Cơ sở 1 Nhà Thuốc Long Tâm', 'MAIN', 10000, 'Long Tâm', '199 Đường Giải Phóng - P. Đồng Tâm - Q. Hai Bà Trưng - TP. Hà Nội', '02438694014'),
(TRUE, 'Cơ sở 2 Nhà Thuốc Long Tâm', 'SUB', 10000, 'Long Tâm', '109 Đường Giải Phóng - P. Đồng Tâm - Q. Hai Bà Trưng - TP. Hà Nội', '02438690061'),
(TRUE, 'Cơ sở 3 Nhà Thuốc Long Tâm', 'SUB', 10000, 'Long Tâm', '127 Đường Giải Phóng - P. Đồng Tâm - Q. Hai Bà Trưng - TP. Hà Nội', '02438969883'),
(TRUE, 'Cơ sở 4 Nhà Thuốc Long Tâm', 'SUB', 10000, 'Long Tâm', '458 Đường Minh Khai - P. Vĩnh Tuy - Q. Hai Bà Trưng - TP. Hà Nội', '02473061996');

-- Inserting into role
INSERT INTO public.role (name, type)
VALUES
('Staff', 'STAFF'),
('Manager', 'MANAGER'),
('Admin', 'ADMIN');

-- Inserting into user
INSERT INTO public."user" (email, first_name, last_name, password, phone, status, username, branch_id)
VALUES
('admin@gmail.com', 'Admin', 'User', '$2a$10$OcIiq4k5s6ZHPWNT93GYOuJWLPnHuvkHVb/RoGlHxMVC73pNPCMBO', '0987654321', 'ACTIVATE', 'admin12', 1),
('manager@gmail.com', 'Manager', 'User', '$2a$10$lHFL5C1XxJKdqNHvB3wYDuT.ZleIKsJvcHA9MyX4HR37GocNVkK1a', '0987654322', 'ACTIVATE', 'manager12', 1),
('staff@gmail.com', 'Employee', 'User', '$2a$10$lHFL5C1XxJKdqNHvB3wYDuT.ZleIKsJvcHA9MyX4HR37GocNVkK1a', '0987654323', 'ACTIVATE', 'staff12', 1),
('ha@gmail.com', 'Trúc', 'Hà', '$2a$10$lHFL5C1XxJKdqNHvB3wYDuT.ZleIKsJvcHA9MyX4HR37GocNVkK1a', '0987654324', 'ACTIVATE', 'trucha', 2),
('duong@gmail.com', 'Chu', 'Dương', '$2a$10$lHFL5C1XxJKdqNHvB3wYDuT.ZleIKsJvcHA9MyX4HR37GocNVkK1a', '0987654325', 'ACTIVATE', 'chuduong', 2),
('thuong@gmail.com', 'Văn', 'Thượng', '$2a$10$lHFL5C1XxJKdqNHvB3wYDuT.ZleIKsJvcHA9MyX4HR37GocNVkK1a', '0987654326', 'ACTIVATE', 'thuong', 2),
('thinh@gmail.com', 'Đức', 'Thịnh', '$2a$10$lHFL5C1XxJKdqNHvB3wYDuT.ZleIKsJvcHA9MyX4HR37GocNVkK1a', '0987654327', 'ACTIVATE', 'thinh', 3),
('toan@gmail.com', 'Văn', 'Toàn', '$2a$10$lHFL5C1XxJKdqNHvB3wYDuT.ZleIKsJvcHA9MyX4HR37GocNVkK1a', '0987654328', 'ACTIVATE', 'toan', 3),
('quan@gmail.com', 'Trung', 'Quân', '$2a$10$lHFL5C1XxJKdqNHvB3wYDuT.ZleIKsJvcHA9MyX4HR37GocNVkK1a', '0987654329', 'ACTIVATE', 'quan', 3),
('Huong@gmail.com', 'Thúy', 'Hường', '$2a$10$lHFL5C1XxJKdqNHvB3wYDuT.ZleIKsJvcHA9MyX4HR37GocNVkK1a', '0987654310', 'ACTIVATE', 'huong', 4),
('chi@gmail.com', 'Thanh', 'Chi', '$2a$10$lHFL5C1XxJKdqNHvB3wYDuT.ZleIKsJvcHA9MyX4HR37GocNVkK1a', '0987654311', 'ACTIVATE', 'chi', 4),
('nhi@gmail.com', 'Quỳnh', 'Nhi', '$2a$10$lHFL5C1XxJKdqNHvB3wYDuT.ZleIKsJvcHA9MyX4HR37GocNVkK1a', '0987654312', 'ACTIVATE', 'nhi', 4);

-- Inserting into user_role
INSERT INTO public.user_role (user_id, role_id)
VALUES
(1, 3),  
(2, 2),  
(3, 1),
(4, 1),  
(5, 2),  
(6, 3),
(7, 1),  
(8, 2),  
(9, 3),
(10, 1),  
(11, 2),  
(12, 3);

-- Table: type
INSERT INTO public.type (type_name, type_description)
VALUES
('Kháng sinh', 'Kháng sinh là nhóm thuốc có khả năng tiêu diệt hoặc ức chế sự phát triển của vi khuẩn, dùng để điều trị các bệnh nhiễm trùng. '),
('Thực phẩm chức năng', 'Là sản phẩm được thiết kế để bổ sung vào chế độ ăn uống hàng ngày, cung cấp các dưỡng chất hoặc tác động có lợi cho sức khỏe. Các thực phẩm chức năng không thay thế được thuốc chữa bệnh nhưng có thể hỗ trợ tăng cường sức khỏe, cải thiện chức năng cơ thể, giúp phòng ngừa bệnh tật hoặc hỗ trợ điều trị các tình trạng sức khỏe nhất định.'),
('Thuốc giảm đau - hạ sốt', 'Thuốc giảm đau - hạ sốt dùng để làm giảm đau và hạ nhiệt độ cơ thể khi có sốt hoặc đau nhẹ.'),
('Thuốc chống viêm', 'Thuốc chống viêm được dùng để giảm viêm, sưng và đau do các bệnh lý viêm.'),
('Thuốc điều trị tim mạch', 'Thuốc điều trị tim mạch giúp kiểm soát huyết áp, rối loạn nhịp tim, và các bệnh lý về tim mạch.'),
('Thuốc điều trị tiêu hóa', 'Thuốc điều trị tiêu hóa hỗ trợ trong việc điều trị các bệnh lý liên quan đến dạ dày, ruột và hệ tiêu hóa.'),
('Thuốc kháng histamin (Chống dị ứng)', 'Thuốc kháng histamin giúp giảm các triệu chứng dị ứng như ngứa, sổ mũi, và mề đay.'),
('Thuốc điều trị nội tiết', ' Thuốc điều trị nội tiết can thiệp vào các chức năng cơ thể liên quan đến hormone.'),
('Thuốc điều trị mắt, tai, mũi', 'Là các loại thuốc được sử dụng để điều trị các vấn đề về mắt, tai và mũi, bao gồm các bệnh lý nhiễm trùng, viêm, dị ứng, hoặc các vấn đề khác liên quan đến các cơ quan này.'),
('Thuốc Đông dược', 'Là các loại thuốc được chiết xuất từ nguyên liệu thiên nhiên, chủ yếu là các loại cây cỏ, thảo mộc, khoáng chất, và động vật. Thuốc Đông dược có nguồn gốc từ nền y học cổ truyền phương Đông, đặc biệt là Trung Quốc và Việt Nam, với mục tiêu cân bằng cơ thể và chữa trị bệnh tật bằng cách sử dụng các thành phần tự nhiên.'),
('Thuốc Tiêm - Truyền', 'Là các loại thuốc được đưa vào cơ thể thông qua hình thức tiêm (chích trực tiếp vào cơ thể) hoặc truyền (dung dịch thuốc được đưa vào cơ thể qua đường truyền tĩnh mạch).'),
('Thuốc Tim Mạch', 'Là các loại thuốc được sử dụng để điều trị các bệnh lý liên quan đến tim và mạch máu, bao gồm các rối loạn về huyết áp, nhịp tim, bệnh mạch vành, suy tim, đột quỵ, và các bệnh lý khác liên quan đến hệ tim mạch.'),
('Vật Tư Y Tế', 'Là các thiết bị, dụng cụ, sản phẩm hoặc vật liệu được sử dụng trong chăm sóc sức khỏe, điều trị bệnh, chẩn đoán và phục hồi chức năng. Chúng giúp bác sĩ và nhân viên y tế thực hiện các thủ thuật, xét nghiệm, phẫu thuật và chăm sóc bệnh nhân.'),
('Khác', 'Các nhóm thuốc khác');

-- Table: category
INSERT INTO public.category (category_name, category_description,  tax_rate)
VALUES
('Thuốc kê đơn', 'Là loại thuốc chỉ được phép bán khi có sự chỉ định của bác sĩ hoặc chuyên gia y tế. ', 5.0),
('Thuốc không kê đơn', 'Là các loại thuốc có thể mua mà không cần sự chỉ định của bác sĩ, vì chúng được cho là an toàn khi sử dụng theo hướng dẫn trên bao bì hoặc từ nhà sản xuất.', 5.0),
('Vitamin C', 'Tăng cường hệ miễn dịch và bảo vệ cơ thể khỏi các bệnh cảm cúm.', 8.0),
('Vitamin D', 'Hỗ trợ hấp thu canxi, duy trì sức khỏe xương và tăng cường hệ miễn dịch.', 8.0),
('Paracetamol', 'Được sử dụng để giảm đau nhẹ và hạ sốt, thường dùng cho các bệnh lý như cảm cúm, đau đầu, đau cơ.', 5.0),
('Ibuprofen', 'Dùng để giảm đau, hạ sốt và điều trị viêm trong các bệnh như viêm khớp, cảm cúm.', 5.0),
('Aspirin', 'Dùng để giảm đau, hạ sốt và chống viêm, đồng thời được sử dụng để ngăn ngừa các cơn', 5.0),
('Amoxicillin', 'Thuốc kháng sinh phổ rộng, dùng để điều trị các bệnh nhiễm trùng do vi khuẩn, như viêm tai, viêm phổi, viêm họng.', 5.0),
('Loratadine', 'Thuốc kháng histamine, dùng để giảm các triệu chứng dị ứng như ngứa, chảy nước mũi, và hắt hơi.', 5.0),
('Cetirizine', 'Giảm các triệu chứng dị ứng, như ngứa, phát ban, nghẹt mũi, và mắt đỏ.', 5.0),
('Omeprazole', 'Dùng để điều trị các bệnh dạ dày, như trào ngược dạ dày thực quản (GERD) và loét dạ dày.', 5.0),
('Loperamide', 'Dùng để điều trị tiêu chảy cấp, giúp giảm tần suất đi tiêu.', 5.0),
('Fluconazole', 'Dùng để điều trị các nhiễm nấm, đặc biệt là nấm đường miệng và nấm âm đạo.', 5.0),
('Atorvastatin', 'Giảm mức cholesterol trong máu, giúp ngăn ngừa các bệnh tim mạch, như nhồi máu cơ tim và đột quỵ.', 5.0),
('Benzoyl Peroxide', 'Dùng để điều trị mụn trứng cá, giảm viêm và ngăn ngừa mụn phát triển.', 5.0),
('Diclofenac', ' Dùng để giảm viêm và đau, đặc biệt trong các bệnh như viêm khớp và đau cơ.', 5.0),
('Dextromethorphan', 'Dùng để giảm ho khan do cảm cúm hoặc các bệnh lý hô hấp.', 5.0),
('Guaifenesin', 'Giúp làm loãng đờm và dễ dàng ho ra, điều trị ho và cảm cúm', 5.0),
('Khác', 'Các loại thuốc khác', 8.0);

-- Table: manufacturer
INSERT INTO public.manufacturer (address, email, manufacturer_name, origin, phone_number, status, tax_code)
VALUES
('Số 43, Đường số 8, VSIP, P. Bình Hòa, TP. Thuận An, T. Bình Dương12', 'BOSTON@gmail.com', 'CÔNG TY CỔ PHẦN DƯỢC PHẨM BOSTON VIỆT NAM', 'VN', '0888160699', TRUE, '0101234557'),
('288 Bis Nguyễn Văn Cừ, P. An Hòa, Q. Ninh Kiều, TP. Cần Thơ', 'dhgpharma@dhgpharma.com.vn', 'Công ty Cổ phần Dược Hậu Giang', 'VN', '02923891433', TRUE, '0101234551'),
('75 Yên Ninh, Ba Đình, Hà Nội, Việt Nam', 'info@traphaco.com.vn', 'Công ty cổ phần Traphaco', 'VN', '02436814910', TRUE, '0101234552'),
('170 Nguyễn Huệ, Phường 7, Tuy Hòa, Phú Yên', 'hcns@pymepharco.com', 'CÔNG TY DƯỢC PHẨM PYMEPHARCO', 'VN', '02573829165', TRUE, '0101234553'),
('số 04 đường 30/4, phường 1, Tp Cao Lãnh, tỉnh Đồng Tháp', 'imp@imexpharm.com', 'CÔNG TY DƯỢC PHẨM IMEXPHARM', 'VN', '0888160688', TRUE, '0101234554'),
('Số 66 Quốc Lộ 30 - Phường Mỹ Phú - TP. Cao Lãnh - Tỉnh Đồng Tháp', 'domesco@domesco.com', 'Công ty cổ phần xuất nhập khẩu y tế DOMESCO ', 'VN', '02773859370', TRUE, '0101234555'),
('498 Nguyễn Thái Học, Phường Quang Trung, Thành Phố Quy Nhơn, Tỉnh Bình Định', 'info@bidiphar.com', 'Công ty cổ phần Dược - Trang thiết bị Y tế Bình Định', 'VN', '0888160691', TRUE, '0101234556'),
('10A Quang Trung - Hà Đông - Hà Nội', 'duochatay@gmail.com', 'Công ty Cổ phần dược phẩm Hà Tây', 'VN', '02433522525', TRUE, '0101234558'),
('1017 - Hồng Bàng, Q.6 - TP.HCM', 'info@opcpharma.com', 'Công ty cổ phần Dược phẩm OPC', 'VN', '0888160692', TRUE, '0101234559'),
('Lô 201-02-03A, KCN Tân Thuận, phường Tân Thuận Đông, quận 7, thành phố Hồ Chí Minh', 'svp@savipharm.com.vn', 'Công ty Cổ phần Dược Phẩm SaVi', 'VN', '0837700144', TRUE, '0101234510'),
('367 Nguyễn Trãi, P.Nguyễn Cư Trinh, Q.1, TP. Hồ Chí Minh.', 'contact@pharmedic.com.vn', 'Công ty CP Dược Phẩm Dược Liệu PHARMEDIC', 'VN', '0987654321', TRUE, '0101234511');

-- Table: supplier
INSERT INTO public.supplier (address, email, fax_number, phone_number, status, supplier_name, tax_code)
VALUES
('Thôn Cầu Đất, Xã Phượng Sơn, Huyện Lục Ngạn, Bắc Giang', 'pharmaftp@gmail.com', '024-39448881', '0378008493', TRUE, 'Công Ty TNHH Đầu Tư Phát Triển Nguyên Liệu Dược Future', '0101234561'),
('Số 26 Ngõ 36 Đường Thượng Hội, X. Tân Hội, H. Đan Phượng, Hà Nội', 'sales.lehaoco@gmail.com', '024-39448882', '02437190219', TRUE, 'Công Ty TNHH Lê Hào', '0101234562'),
('289 Đinh Bộ Lĩnh, P. 26, Q. Bình Thạnh, TP. Hồ Chí Minh (TPHCM)', 'info@difoco.com', '024-39448883', '02866857787', TRUE, 'Công Ty Cổ Phần Difoco', '0101234563'),
('186 Định Công Hạ, P. Định Công, Q. Hoàng Mai, Hà Nội', 'kimluan32@gmail.com', '024-39448884', '0919559698', TRUE, 'Công Ty Cổ Phần Dưỡng Dược Vĩnh Kim', '0101234564'),
('35 Đường 3/2, P. 11, Q. 10, TP. Hồ Chí Minh (TPHCM)', 'bichlienmiracle@gmail.com', '024-39448885', '02838355005', TRUE, 'Công Ty TNHH Mỹ Phẩm EV Princess', '0101234565'),
('37/5B Trung Mỹ Tây, Trung Chánh, Hóc Môn, TP. Hồ Chí Minh (TPHCM)', 'info@neemtree.vn', '024-39448886', '02871066869', TRUE, 'Công Ty Cổ Phần Neemtree', '0101234566'),
('99 Đường Số 8, P. 4, Q. 8, TP. Hồ Chí Minh (TPHCM)', 'rxbhongphong@gmail.com', '024-39448887', '0902216004', TRUE, 'Rượu Thuốc Xoa Bóp Gia Truyền Hồng Phong', '0101234567'),
('Số 725, Đ. Yên Ninh, TP. Yên Bái, Yên Bái', 'ypharco@ypharco.com', '024-39448888', '02163852523', TRUE, 'Công Ty CP Dược Phẩm Yên Bái - Ypharco', '0101234568'),
(' Xã Đại Yên, Chương Mỹ, Hà Nội', 'info@cagaileosadu.com.vn', '024-39448889', '0972339095', TRUE, 'Công Ty CP Nông Nghiệp Công Nghệ Cao Thăng Long', '0101234569'),
('475 Đoàn Văn Bơ, Phường 14, Quận 4, TP. Hồ Chí Minh (TPHCM)', 'xuandiemthaicorp@gmail.com', '024-39448810', '09030703384', TRUE, 'Eva Shop', '0101234570'),
('Số 127, Tổ 1, Khu 1, Phường Hùng Thắng, Tp Hạ Long, Quảng Ninh', 'quangninhbakichtim@gmail.com', '024-39448811', '02033846333', TRUE, 'Doanh Nghiệp Tư Nhân Trọng Đức', '0101234571'),
('Đường Điện Biên Phủ, TT. Nam Ban, H. Lâm Hà, Lâm Đồng', 'cayduoclieutpp6886@gmail.com', '024-39448813', '02633852668', TRUE, 'Công Ty Cổ Phần Dịch Vụ Thương Mại Và Chiết Xuất Cây Dược Liệu TPP', '0101234573'),
('91 Ngõ 381 Nguyễn Khang, Cầu Giấy, Hà Nội Hà Nội', 'Bacsychuyenkhoangxoang@hotmail.com', '024-39448814', '0988689289', TRUE, 'Công Ty Hoa Bảo', '0101234574'),
('1/13/1 Nguyễn Đình Khơi, P. 4, Q. Tân Bình, TP. Hồ Chí Minh (TPHCM)', 'thaoduocthiennhienvn@gmail.com', '024-39448815', '02838117762', TRUE, 'Công Ty TNHH MTV Thiện Oanh', '0101234575'),
('Số 410, Tầng 4, Raipur', 'vinayaktradingryp@gmail.com', '024-39448816', '0585701699', TRUE, 'Vinayak Trading Company', '0101234576'),
('A2 Võ Thị Sáu, P. Quyết Thắng, TP. Biên Hòa, Đồng Nai', 'contact@1969s.com', '024-39448812', '0888160677', TRUE, 'Công Ty TNHH TRADING TAK', '0101234572');

INSERT INTO public.unit_of_measurement (unit_name)
VALUES
('Hộp'),
('Vỉ'),
('Viên'),
('Thùng'),
('Gói'),
('Chai'),
('Túi'),
('Ống');

-- Table: storage_location
INSERT INTO public.storage_location (shelf_name)
VALUES
('A'),
('B'),
('C'),
('D'),
('E'),
('F'),
('G'),
('H'),
('I');

-- Inserting into product
INSERT INTO public.product (active_ingredient, excipient, formulation, inbound_price, product_name, registration_code, sell_price, status, url_image, base_unit_id, category_id, manufacturer_id, type_id)
VALUES
('Vitamin B1 (Thiamin nitrat)', 'Tinh bột mì, lactose, gelatin, nipagin, nipasol, magnesi stearat, nước tinh khiết', 'Viên nén', 10000, 'EtonciB1', 'GC-215-13', 15000, 'CON_HANG', null, 1, 1, 1, 1),
('Vitamin B6', 'Tinh bột sắn, tinh bột mì, lactose, cellulose 80, bột talc, magnesi stearat, nước tinh khiết', 'Viên nén', 20000, 'EtonciB6', 'GC-216-13', 25000, 'CON_HANG', null, 1, 1, 1, 1),
('Hydroxocobalamin acetat', 'Natri clorid, methylparaben, propylparaben, nước cất pha tiêm vừa đủ 2 ml', 'Dung dịch  tiêm', 11000, 'Dodevifort', 'GC-217-13', 11000, 'CON_HANG', null, 6, 1, 1, 1),
('Cao khô Bình vôi; Cao khô Lá vông nem; Liên nhục, Quyết minh tử; Hoài sơn', 'Dưỡng tân an thần, gây ngủ, bổ ngũ tạng', 'Viên nang cứng', 13000, 'An thần ACP', 'GC-219-14', 18000, 'CON_HANG', null, 1, 1, 1, 1),
('Diệp hạ châu; Nhân trần; Bồ công anh', null, 'Viên nang cứng', 140000, 'Bình can ACP', 'GC-220-14', 17000, 'CON_HANG', null, 1, 1, 1, 1),
('Cát cánh; Kim ngân hoa; Cam thảo; Kinh giới;  Ngưu bàng tử;  Liên kiều; Đạm trúc diệp; tinh dầu Bạc hà', 'Magnesistearat', 'Viên nang cứng', 13000, 'Giải cảm liên ngân', 'GC-221-14', 19000, 'CON_HANG', null, 1, 1, 1, 1),
('Rễ Đinh lăng; Cao lá Bạch quả', 'Tinh bột sắn, Magnesi carbonat nhẹ, Lactose, Talc, TiO2, HPMC, PEG 6000, Magnesi stearat, sắt III oxyd', 'Viên nén bao phim', 20000, 'Hoạt huyết dưỡng não ACP', 'GC-222-14', 30000, 'CON_HANG', null, 1, 1, 1, 1),
('Cao khô Kim tiền thảo; Cao khô râu ngô', 'Tinh bột sắn, magnesi carbonat, lactose, magnesi stearat, talc, titan dioxid, HPMC', 'Viên nén bao phim', 11000, 'Kim tiền thảo râu ngô', 'GC-223-14', 18000, 'CON_HANG', null, 1, 1, 1, 1),
('Cao khô Thục địa; Cao khô Hoài sơn; Cao khô Sơn thù; Cao khô Mẫu đơn bì; Cao khô Trạch tả; Cao khô Phục linh', 'Magnesi stearat, tinh bột sắn, Acid benzoic', 'Viên nang cứng', 15000, 'Lục vị ACP', 'GC-224-14', 21000, 'CON_HANG', null, 1, 1, 1, 1),
('Cao khô Hy thiêm; Cao khô Ngũ gia bì gai; Cao khô Thiên niên kiện; Cao khô Cẩu tích; Cao khô Thổ phục linh', 'Magnesi stearat, tinh bột sắn', 'Viên nang cứng', 25000, 'Phong thấp ACP', 'GC-225-14', 40000, 'CON_HANG', null, 1, 1, 1, 1),
('Bách bộ; Mạch môn; Cát cánh; Trần bì; Cam thảo, Menthol, tinh dầu Bạc hà', 'Lactose, Đường trắng, Magnesi stearat, Glucose acid benzoic', 'Viên nén ngậm', 21000, 'Viêm ngậm ho bổ phế', 'GC-226-14', 25000, 'CON_HANG', null, 1, 1, 1, 1),
('ích mẫu; hương phụ; ngải cứu', null, 'Viên nang cứng', 11000, 'Viên nang ích mẫu', 'GC-228-14', 19000, 'CON_HANG', null, 1, 1, 1, 1),
('Cao khô Diếp cá (tương đương 750 mg Diếp cá) 75 mg; Bột rau má 300 mg', 15000, 'Viên nang mềm', null, 'Cenditan', 'GC-229-14', 21000, 'CON_HANG', null, 1, 1, 1, 1),
('Bột Rau má (tương đương 7500 rau má tươi) 750 mg', null, 'Viên nén bao phim', 20000, 'Centasia', 'GC-230-14', 25000, 'CON_HANG', null, 1, 1, 1, 1),
('Cao khô Actiso (tương đương 5800 lá tươi Actiso) 40 mg; Bột rau má 300 mg', null, 'Viên nang mềm', 21000, 'Centhionin', 'GC-231-14', 30000, 'CON_HANG', null, 1, 1, 1, 1),
('Sorbitol 5g', null, 'Thuốc bột uống', 20000, 'Sorbitol delalande', 'GC-232-14', 29000, 'CON_HANG', null, 1, 1, 1, 1),
('Vitamin B1 5 mg; Vitamin B6 5 mg; Vitamin B12 10 mcg; Sắt (dưới dạng sắt sulfat) 30 mg', null, 'Viên nang mềm', 17000, 'Neublod', 'GC-233-14', 23000, 'CON_HANG', null, 1, 2, 2, 2),
('Calci (dưới dạng Calci glucoheptonat 500 mg) 40,8 mg; Vitamin D2 200 IU; Vitamin C 30 mg; Vitamin PP 20 mg', 'null', 'Viên nang mềm', 20000, 'Ibatonic-Calci', 'GC-234-14', 28000, 'CON_HANG', null, 1, 2, 2, 2),
('Lysin hydroclorid 15 mg; Vitamin B1 10 mg; Vitamin B2 5 mg; Vitamin B6 10 mg; Vitamin PP 15 mg; Vitamin E 5 IU; Calci glycerophosphat 10 mg;', null, 'Viên nang mềm', 29000, 'Ibatonic-F', 'GC-235-14', 50000, 'CON_HANG', null, 1, 1, 1, 1),
('Paracetamol 500mg', null, 'Viên nén', null, 'Paracetamol Winthrop', 'GC-236-15', null, 'CON_HANG', null, 1, 2, 2, 2),
('Cao khô lá Bạch quả ( chứa 24% flavonoid)', 'lactose monohydrat, microcrystalline cellulose, nipagin, nipasol, talc, ', 'Viên nén bao phim', null, 'Aulakan', 'GC-237-15', null, 'CON_HANG', null, 1, 2, 2, 2),
('Cao khô lá Bạch quả 60 mg', null, 'Viên nén bao phim', null, 'Aulakan-F', 'GC-238-1', null, 'CON_HANG', null, 1, 2, 2, 2),
('Bột Nghệ ; Bột Mai mực', 'Lactose monohydrat, Tinh bột Ngô, Povidon K90, Nipagin, Magnesi stearat, Talc, Colloidal silica khan (Aerosil 200),', 'Viên nén bao phim', null, 'Oscumin', 'GC-239-15', null, 'CON_HANG', null, 1, 2, 2, 2),
('Cao khô Kim tiền thảo (tương đương 1,5 g Kim tiền thảo) 120 mg', null, 'Viên nén bao phim', null, 'Kim Tiền Thảo PMC', 'GC-240-15', null, 'CON_HANG', null, 1, 2, 2, 2),
('Cao khô Kim tiền thảo (tương đương 2284,8 mg Kim tiền thảo) 160 mg;', null, 'Viên nang cứng', null, 'Deston', 'GC-241-15', null, 'CON_HANG', null, 1, 2, 2, 2),
('Mỗi 6ml chứa: Eucalyptol 2100mg; Menthol 2340mg; Methyl salicylat 258mg; Camphor 102mg', null, 'Dầu gió', null, 'Dầu gió kim', 'GC-242-15', null, 'CON_HANG', null, 6, 2, 2, 2),
('Cao khô lá Bạch quả', 'Povidon 30, Lactose monohydrat, Primellose, Magnesi stearat, Avicel M101, HPMC 615, PEG 6000, Titan dioxyd, bột Talc, Sắt oxyd đỏ', 'Viên nén bao phim', null, 'Gentlemax', 'GC-243-16', null, 'CON_HANG', null, 1, 2, 2, 2),
('Cefotaxim', null, 'Bột pha tiêm', null, 'Claforan', 'GC-244-16', null, 'CON_HANG', null, 1, 2, 2, 2),
('Lamivudin', 'Tinh bột bắp, Lactose, Avicel 102, PVP, DST, Magnesi stearat, HPMC 615, PEG 6000, Titan dioxyd, Talc, Sắt oxyd đỏ, Sắt oxyd đen, Sắt oxyd vàng', 'Viên nén bao phim.', null, 'Docyclos', 'GC-245-16', null, 'CON_HANG', null, 1, 2, 2, 2),
('Ciprofloxacin (dưới dạng Ciprofloxacin HCl) 500mg', null, 'Viên nén  bao phim', null, 'Tamisynt 500mg', 'GC-246-16', null, 'CON_HANG', null, 1, 2, 2, 2),
('Cao khô lá bạch quả', 'Sáp ong, lecithin, dầu đậu nành, gelatin 200 bloom, glycerin, methyl paraben, propyl paraben, sorbitol lỏng, ethyl vanillin, titan dioxyd', 'Viên nang mềm', null, 'Ginknex', 'GC-247-16', null, 'CON_HANG', null, 1, 2, 2, 2),
('Mỗi 100 ml cao lỏng chứa chất chiết được từ các dược liệu tương đương với: Lạc tiên  60g; Lá Vông 36g; Tang diệp 12g; Liên tâm 2,64g', null, 'Cao lỏng', null, 'Cao lạc tiên BVP', 'GC-248-16', null, 'CON_HANG', null, 1, 2, 2, 2),
('Dexamethason (dưới dạng Dexamethason acetat) 0,5 mg', null, 'Viên nén (hồng-vàng)', null, 'Dexamethason 0,5mg', 'GC-259-16', null, 'CON_HANG', null, 1, 2, 2, 2),
('Prednison 5 mg', null, 'Viên nén (màu xanh)', null, 'Prednison 5 mg', 'GC-260-16', null, 'CON_HANG', null, 1, 2, 2, 2),
('Bột củ tỏi ; Bột thân rễ nghệ', 'Natri starch glycolat, microcrystalline cellulose 101, magnesi stearat, tinh bột ngô, lactose monohydrat, ', 'Viên nén bao phim', null, 'Garlicur - G', 'GC-263-17', null, 'CON_HANG', null, 1, 2, 2, 2),
('Prednison 5 mg', null, 'Viên nén (màu trắng)', null, 'Prednisone 5mg', 'GC-264-17', null, 'CON_HANG', null, 1, 2, 2, 2),
('Metformin HCl 850 mg', null, 'Viên nén bao phim', null, 'Metformin Stada 850 mg', 'GCXK-6-16', null, 'CON_HANG', null, 1, 2, 2, 2),
('Mỗi 10g chứa: Sinh địa 0,333g; Hy thiêm thảo 1,583g; Ngưu tất 1,353g; Cẩu tích 1,125g; Quế chi tiêm 0,316g; Ngũ gia bì 0,883g; Mật ong 1g; Đường kính 4,8g', null, 'Viên hoàn mềm', null, 'Hoàn phong thấp', 'GC-265-17', null, 'CON_HANG', null, 1, 2, 2, 2),
('Cao Actiso (tương đương với 11725 mg lá actiso tươi)', 'Dầu cọ; Sáp ong trắng; Lecithin; Dầu đậu nành; Propyl paraben; Methyl paraben; Ethyl vanillin; Titan dioxyd;', 'Viên nang mềm', null, 'Hepa Extra', 'GC-266-17', null, 'CON_HANG', null, 1, 2, 2, 2),
('Mỗi chai 300 ml chứa dịch chiết từ các dược liệu: Nhân sâm 12g; Đương quy 12g; Thục địa 35g; Ba kích 14g; Hoàng kỳ 10g; Bạch truật 10g;', null, 'Cao lỏng', null, 'Sâm qui tinh', 'GC-267-17', null, 'CON_HANG', null, 1, 2, 2, 2),
('Mỗi chai 100ml chứa dịch chiết từ các dược liệu: Hạnh nhân 14g; Cát cánh 14g; Tang bạch bì 14g; Bạc hà 14g; Tô diệp 14g; Bách bộ 7,5g;', null, 'Viên nén', null, 'Thuốc ho trẻ em', 'GC-268-17', null, 'CON_HANG', null, 1, 2, 2, 2),
('Cao mật lợn khô; Tỏi khô; Cao đặc Actis; Than hoạt tính', null, 'Viên nang cứng', null, 'Chorlatcyn', 'GC-269-17', null, 'CON_HANG', null, 1, 2, 2, 2),
('Cao khô lá Bạch quả ; Cao đặc rễ Đinh lăng', 'Calci carbonat, lactose monohydrat, croscarmellose natri, natri starch glycolat, aerosil, microcrystalline ', 'Viên nén bao phim', null, 'Hoạt huyết kiện não', 'GC-270-17', null, 'CON_HANG', null, 1, 2, 2, 2),
('Cao khô vỏ cây Pygeum africanum (15:1)', 'sáp ong,  lecithin, 2-tert-butyl-1 4-dimethoxybenzene, dầu đậu nành gelatinm glycerin methyl paraben, propyl', 'Viên nang mềm', null, 'Guzman', 'GC-271-17', null, 'CON_HANG', null, 1, 2, 2, 2),
('Magnesium lactat dihydrat 470mg; Pyridoxin HCl 5mg', null, 'Viên nén bao phim', null, 'Magne B6 - BVP', 'GC-272-17', null, 'CON_HANG', null, 1, 2, 2, 2),
('Dextromethorphan hydrobromid 10 mg', null, 'Viên nén', null, 'Dextromethorphan 10mg', 'GC-273-17', null, 'CON_HANG', null, 1, 2, 2, 2),
('Acetylcystein', 'aspartame, hương cam, Yellow color No.6, lactose monohydrate', 'Thuốc cốm', null, 'Acemuc 200mg', 'GC-274-17', null, 'CON_HANG', null, 1, 3, 3, 3),
('Domperidon (dưới dạng Domperidon maleat)', 'Lactose khan, tinh bột bắp, cellulose vi tinh thể, tinh bột tiền gelatin hóa, povidon K90, ', 'Viên nén bao phim', null, 'Motilium-M', 'GC-275-17', null, 'CON_HANG', null, 1, 3, 3, 3),
('Bột tỏi 240 mg; Bột nghệ 10 mg', null, 'Viên nang cứng', null, 'Alixina - N', 'GC-276-17', null, 'CON_HANG', null, 1, 3, 3, 3),
('Mỗi viên chứa 224 mg cao khô hỗn hợp dược liệu tương đương: Dâm dương hoắc 200mg; Xuyên tiêu 200mg; Ngưu tất 200mg; Ba kích 200mg;', null, 'Viên nén bao phim', null, 'Khởi đơn dương', 'GC-277-17', null, 'CON_HANG', null, 1, 3, 3, 3),
('Tinh dầu gừng', 'dầu đỗ tương, gelatin, glycerin, sorbitol lỏng, nipagin, nipasol, vanilin, oxyd sắt vàng, brown HT', 'Viên nang mềm', null, 'Ziber', 'GC-278-17', null, 'CON_HANG', null, 1, 3, 3, 3),
('Methylprednisolon', 'Tinh bột mì, Lactose, Avicel 102, PVP K90, Natri lauryl sulfat, Magnesi stearat, Primellose', 'Viên nén', null, 'Dotinoin', 'GC-279-17', null, 'CON_HANG', null, 1, 3, 3, 3),
('Bisoprolol fumarat 2,5mg', null, 'Viên nén bao phim', null, 'Bisoprolol 2.5', 'GC-280-17', null, 'CON_HANG', null, 1, 3, 3, 3),
('Bisoprolol fumarat 5mg', null, 'Viên nén bao phim', null, 'Bisoprolol 5', 'GC-281-17', null, 'CON_HANG', null, 1, 3, 3, 3),
('Cao khô Diệp hạ châu 250mg', null, 'Viên nén bao phim', null, 'Diệp hạ châu PMC', 'GC-282-17', null, 'CON_HANG', null, 1, 3, 3, 3),
('Captopril', 'Lactose monohydrat, cellulose vi tinh thể, croscarmellose natri, cellulose bột, magnesi stearat', 'Viên nén', null, 'Hurmat 25mg', 'GC-283-17', null, 'CON_HANG', null, 1, 3, 3, 3),
('Levofloxacin (dưới dạng Levofloxacin hemihydrat) 250mg', 'Cellulose vi tinh thể, hypromellose, crospovidon', 'Viên nén  bao phim', null, 'Ozanier 250mg', 'GC-284-17', null, 'CON_HANG', null, 1, 3, 3, 3),
('Ích mẫu ; Ngải cứu ; Hương phụ ; Thục địa ; Bạch thược ; Đương qui ; Xuyên khung', null, 'Viên nang cứng', null, 'Ích mẫu điều kinh', 'GC-285-17', null, 'CON_HANG', null, 1, 3, 3, 3),
('Mỗi 100ml dung dịch chứa: Paracetamol 1000 mg', null, 'Dung dịch tiêm truyền', null, 'RVPara', 'GC-287-17', null, 'CON_HANG', null, 1, 3, 3, 3),
('Paracetamol 650 mg', null, 'Viên nén bao phim', null, 'Bivinadol Power', 'GC-288-18', null, 'CON_HANG', null, 1, 3, 3, 3),
('Mỗi 100 ml dung dịch chứa: Ofloxacin 200 mg', null, 'Dung dịch tiêm truyền', null, 'Oplatin', 'GC-289-18', null, 'CON_HANG', null, 1, 3, 3, 3),
('Mỗi chai 150 ml dung dịch chứa: Levofloxacin (dưới dạng Levofloxacin hemihydrat) 750 mg', null, 'Dung dịch tiêm truyền', null, 'Rvlevo 750', 'GC-290-18', null, 'CON_HANG', null, 1, 3, 3, 3),
('Paracetamol 500mg; Codein phosphat (dưới dạng Codein phosphat hemihydrat) 30mg', null, 'Viên nén bao phim', null, 'Hapacol Codein', 'GC-291-18', null, 'CON_HANG', null, 1, 3, 3, 3),
('Prednison', 'tinh bọt mì, lactose, pvp, natri starch glycolat, magnesi stearat', 'Viên nang cứng (xanh-ngọc trai)', null, 'Prednison 5mg', 'GC-292-18', null, 'CON_HANG', null, 1, 3, 3, 3),
('Levofloxacin (dưới dạng Levofloxacin hemihydrat)', 'cellulose vi tinh thể, hypromellose, cropovidon , magnesi stearat', 'Viên nén bao phim', null, 'Ozanier 500mg', 'GC-293-18', null, 'CON_HANG', null, 1, 3, 3, 3),
('Acetylcystein', 'aspartame, hương cam, Yellow color No.6, lactose monohydrate', 'Thuốc cốm', null, 'Acemuc 100mg', 'GC-294-18', null, 'CON_HANG', null, 1, 3, 3, 3),
('Promethazin 2%', null, 'Kem bôi ngoài da', null, 'Phenergan', 'GC-295-18', null, 'CON_HANG', null, 1, 3, 3, 3),
('Amoxicillin (dưới dạng Amoxicillin trihydrat)', 'Colloidal silicon dioxyd, sodium starch glyconat, magnesi stearat', 'Viên nang cứng (xanh bạc - nâu tím bạc)', null, 'AmoDHG 500', 'GC-296-18', null, 'CON_HANG', null, 1, 3, 3, 3),
('Vitamin A (Retinol palmitat) 2000 IU; Vitamin D3 (cholecalciferol) 250 IU', 'Dầu dậu nành, gelatin, sorbitol 70%, glycerin, nipazil, ', 'Viên nang mềm', null, 'AD Tamy', 'GC-297-18', null, 'CON_HANG', null, 1, 3, 3, 3),
('Prednison', 'Lactose, Tinh bột mì, Cellulose vi tinh thể PH101, Natri lauryl sulfat, Magnesi stearat, Colloidal silicon', 'Viên nén (màu hồng)', null, 'Prednison 5mg', 'GC-298-18', null, 'CON_HANG', null, 1, 3, 3, 3),
('Ciprofloxacin; (dưới dạng Ciprofloxacin HCl)', null, 'Viên nén bao phim', null, 'Lufocin', 'GC-299-18', null, 'CON_HANG', null, 1, 3, 3, 3),
('Paracetamol 500mg', null, 'Viên nén', null, 'Paracetamol Stada 500 mg', 'GCXK-7-16', null, 'CON_HANG', null, 1, 3, 3, 3),
('Bromhexin hydrochlorid 8mg', 'Tinh bột sắn, Lactose monohydrat, Gelatin, PVP.K30, Quinolin yellow, Talc, Magnesi stearat vừa đủ 1 viên', 'Viên nén (màu vàng)', null, 'Bromhexin', 'GC-300-18', null, 'CON_HANG', null, 1, 3, 3, 3),
('Paracetamol 500mg', null, 'Viên nén', null, 'Paracetamol', 'GC-301-18', null, 'CON_HANG', null, 1, 3, 3, 3),
('Piroxicam 10mg', null, 'Viên nang cứng', null, 'Pỉroxicam', 'GC-302-18', null, 'CON_HANG', null, 1, 3, 3, 3),
('Alimemazin tartrat 5mg', 'Lactose monohydrat, Tinh bột sắn, Gelatin, Magnesi stearat, Talc, ', 'Viên nén bao phim', null, 'Toussolène', 'GC-303-18', null, 'CON_HANG', null, 1, 3, 3, 3),
('Lộc nhung; Nhân sâm; Hoàng kỳ; Đương quy; Liên nhục; Trần bì; Mẫu lệ; Nhục thung dung; Ngũ vị tử; hoài sơn; bạch truật; sơn thù; hoàng bá; ba kích', null, 'Viên hoàn cứng', null, 'Khởi dương hoàn', 'GC-304-18', null, 'CON_HANG', null, 1, 4, 4, 4),
('Cao khô lá bạch quả', null, 'Viên nang mềm', null, 'Ginkfa', 'GC-308-18', null, 'CON_HANG', null, 1, 4, 4, 4),
('Mỗi 6g hoàn cứng chứa: Lộc nhung 0,15g; Nhân sâm 0,75g; Hoàng kỳ 0,7g;', 'Đường trắng, tinh bột sắn, bột talc', 'Viên hoàn cứng', null, 'Hoàn sinh lực', 'GC-309-18', null, 'CON_HANG', null, 1, 4, 4, 4),
('Doxycyclin (dưới dạng Doxycyclin hyclat) 100mg', 'Lactose monohydrat, pregelatinized starch, magnesi stearat', 'Viên nang cứng (xanh lá cây đậm-xanh da trời)', null, 'Basicillin 100mg', 'GC-310-18', null, 'CON_HANG', null, 1, 4, 4, 4),
('Sulpirid 50mg', null, 'Viên nang cứng', null, 'Dogwazin', 'GC-311-19', null, 'CON_HANG', null, 1, 4, 4, 4),
('Nicotinamid', null, 'Viên nén bao phim', null, 'Nitrosol', 'GC-312-19', null, 'CON_HANG', null, 1, 4, 4, 4),
('Mỗi viên chứa L-Arginine HCL 500mg', null, 'Viên nén bao phim', null, 'Oracgine', 'GC-313-19', null, 'CON_HANG', null, 1, 4, 4, 4),
('Cao khô lá bạch quả', null, 'Viên nén bao phim', null, 'Boakye', 'GC-314-19', null, 'CON_HANG', null, 1, 4, 4, 4),
('Aciclovir', 'Lactose monohydrate, microcrystalline cellulose, croscarmellose sodium, magnesium stearate, erythrosine aluminium lake (E127)', 'Viên nén', null, 'Aceralgin 400mg', 'GC-315-19', null, 'CON_HANG', null, 1, 4, 4, 4),
('Aciclovir', 'Lactose monohydrate, microcrystalline cellulose, croscarmellose sodium, magnesium stearate, blue lake (E132)', 'Viên nén', null, 'Aceralgin 800mg', 'GC-316-19', null, 'CON_HANG', null, 1,4, 4, 4),
('Clorpheniramin maleat 4mg', null, 'Viên nang cứng (màu tím - vàng)', null, 'Chlorpheniramin', 'GC-317-19', null, 'CON_HANG', null, 1, 4, 4, 4),
('Paracetamol 300mg; Ibuprofen 200mg; Cafein 20mg', null, 'Viên nang cứng', null, 'Ibuparavic', 'GC-318-19', null, 'CON_HANG', null, 1, 4, 4, 4),
('Củ bình vôi; Long nhãn; Liên nhục; Táo nhân; Lạc tiên; Thục địa; Hoài sơn', null, 'Viên hoàn mềm', null, 'Bổ tâm an thần', 'GC-319-19', null, 'CON_HANG', null, 1, 1, 1, 1),
('Đỗ trọng; Ngưu tất; Tục đoạn; Phá cố chỉ; Ý dĩ; Đương quy; Bạch chỉ; Hạt sen; Cẩu tích; Độc hoạt; ', null, 'Viên hoàn cứng', null, 'Khớp lưng tọa - NB', 'GC-320-19', null, 'CON_HANG', null, 1, 4, 4, 4),
('Cetirizin dihydroclorid 10mg', null, 'Viên nén bao phim', null, 'Aryzaltec', 'GC-321-19', null, 'CON_HANG', null, 1, 4, 4, 4),
('Cetirizin dihydroclorid 10mg', null, 'Viên nén bao phim', null, 'Cetirizin', 'GC-322-19', null, 'CON_HANG', null, 1, 4, 4, 4),
('Clorpheniramin maleat 4mg', null, 'Viên nén', null, 'Chlorpheniramin', 'GC-323-19', null, 'CON_HANG', null, 1, 4, 4, 4),
('Natri benzoat 50mg; Terpin hydrat 100mg', null, 'Viên nang cứng', null, 'Terpin Benzoat', 'GC-324-19', null, 'CON_HANG', null, 1, 4, 4, 4),
('Paracetamol 500mg; Caffeine 25mg; Phenylephrine hydrochloride 5mg', null, 'Viên nén bao phim', null, 'Panadol cảm cúm', 'GC-325-19', null, 'CON_HANG', null, 1, 4, 4, 4),
('Bromhexin hydroclorid 8mg', null, 'Viên nén (màu xanh)', null, 'Bromhexin', 'GC-326-19', null, 'CON_HANG', null, 1, 4, 4, 4),
('Calcium gluconate 500mg; Cholecalciferol 200UI', null, 'Viên nén bao phim', null, 'Calcium + D', 'GC-327-19', null, 'CON_HANG', null, 1, 4, 4, 4),
('Piroxicam 10mg', null, 'Viên nang cứng', null, 'De-Antilsic', 'GC-328-19', null, 'CON_HANG', null, 1, 4, 4, 4),
('Acid mefenamic 250mg', null, 'Viên nén', null, 'Ipalzac', 'GC-329-19', null, 'CON_HANG', null, 1, 4, 4, 4),
('Nhôm hydroxyd gel khô 200mg; Magnesi hydroxyd 200mg', null, 'Viên nén nhai', null, 'Kizemit-S', 'GC-330-19', null, 'CON_HANG', null, 1, 4, 4, 4),
('Salbutamol (dưới dạng Salbutamol sulfat) 2mg', null, 'Viên nén', null, 'Salbutamol', 'GC-331-19', null, 'CON_HANG', null, 1,4, 4, 4),
('N-Acetyl-DL-Leucin 500mg', null, 'Viên nén', null, 'Taginyl', 'GC-332-19', null, 'CON_HANG', null, 1, 4, 4, 4),
('Imipenem (dưới dạng Imipenem monohydrat); Cilastatin (dưới dạng Cilastatin natri)', null, 'Bột pha tiêm', null, 'Tienam', 'GC3-1-18', null, 'CON_HANG', null, 1, 5, 5, 5),
('Bisoprolol hemifumarat 10mg; Hydroclorothiazid 25mg', null, 'Viên nén bao phim', null, 'Bisoplus Stada 10mg/25mg', 'GCXK-1-16', null, 'CON_HANG', null, 1, 5, 5, 5),
('Lisinopril (dưới dạng Lisinopril dihydrat) 10mg', null, 'Viên nén', null, 'Lisinopril Stada 10 mg', 'GCXK-10-16', null, 'CON_HANG', null, 1, 5, 5, 5),
('Zaltoprofen 80mg', null, 'Viên nén', null, 'Soleton', 'GCXK-11-17', null, 'CON_HANG', null, 1,5, 5, 5),
('Felodipin 10mg', null, 'Viên nén bao phim', null, 'Felodipin Stada 10 mg retard', 'GCXK-12-17', null, 'CON_HANG', null, 1, 5, 5, 5),
('Metformin hydrochlorid 500mg', null, 'Viên nén bao phim', null, 'Metformin Stada 500mg', 'GCXK-13-17', null, 'CON_HANG', null, 1, 5, 5, 5),
('Pantoprazol (dưới dạng Pantoprazol natri sesquihydrat) 40mg', null, 'Viên nén bao phim', null, 'Pantoprazol Stada 40mg', 'GCXK-14-17', null, 'CON_HANG', null, 1, 5, 5, 5),
('Felodipin 2,5mg', null, 'Viên nén bao phim tác dụng kéo dài', null, 'Felodipin Stada 2,5mg retard', 'GCXK-15-18', null, 'CON_HANG', null, 1, 1, 1, 1),
('Ibuprofen 600mg', null, 'Viên nén bao phim', null, 'Ibuprofen Stada 600 mg', 'GCXK-16-18', null, 'CON_HANG', null, 1, 5, 5, 5),
('Lisinopril (dưới dạng Lisinopril dihydrat) 2,5mg', null, 'Viên nén', null, 'Lisinopril Stada 2,5 mg', 'GCXK-17-18', null, 'CON_HANG', null, 1, 5, 5, 5),
('Lisinopril (dưới dạng Lisinopril dihydrat) 20mg', null, 'Viên nén', null, 'Lisinopril Stada 20 mg', 'GCXK-18-18', null, 'CON_HANG', null, 1, 5, 5, 5),
('Lisinopril (dưới dạng Lisinopril dihydrat) 5mg', null, 'Viên nén', null, 'Lisinopril Stada 5 mg', 'GCXK-19-18', null, 'CON_HANG', null, 1, 5, 5, 5),
('Bisoprolol hemifumarat 5mg; Hydroclorothiazid 12,5mg', null, 'Viên nén bao phim', null, 'Bisoplus Stada 5mg/12.5 mg', 'GCXK-2-16', null, 'CON_HANG', null, 1, 5, 5, 5),
('Lisinopril (dưới dạng Lisinopril dihydrat) 10mg ; Hydroclorothiazid 12,5mg', null, 'Viên nén', null, 'Lisiplus Stada 10mg/12,5mg', 'GCXK-20-18', null, 'CON_HANG', null, 1, 5, 5, 5),
('Lisinopril (dưới dạng Lisinopril dihydrat) 20mg ; Hydroclorothiazid 12,5mg', null, 'Viên nén', null, 'Lisiplus Stada 20mg/12,5mg', 'GCXK-21-18', null, 'CON_HANG', null, 1, 5, 5, 5),
('Losartan kali 100mg', null, 'Viên nén bao phim', null, 'Losartan Stada 100 mg', 'GCXK-22-18', null, 'CON_HANG', null, 1, 5, 5, 5),
('Losartan kali 50mg', null, 'Viên nén bao phim', null, 'Losartan Stada 50 mg', 'GCXK-23-18', null, 'CON_HANG', null, 1, 5, 5, 5),
('Bisoprolol hemifumarat 10mg', null, 'Viên nén bao phim', null, 'Bisoprolol Stada 10mg', 'GCXK-3-16', null, 'CON_HANG', null, 1, 5, 5, 5),
('Bisoprolol hemifumarat 5mg', null, 'Viên nén bao phim', null, 'Bisoprolol Stada 5 mg', 'GCXK-4-16', null, 'CON_HANG', null, 1, 5, 5, 5),
('Felodipin 5 mg', null, 'Viên nén bao phim tác dụng kéo dài', null, 'Felodipin Stada 5 mg', 'GCXK-5-16', null, 'CON_HANG', null, 1, 5, 5, 5),
('Acid tranexamic 1g/10ml', null, 'Dung dịch tiêm', null, 'Tranexamic acid 1g <NP>', 'GCXK-8-16', null, 'CON_HANG', null, 1, 5, 5, 5),
('Piracetam 800mg', null, 'Viên nén bao phim', null, 'Piracetam Stada 800 mg', 'GCXK-9-16', null, 'CON_HANG', null, 1, 5, 5, 5),
('Thương truật, Hậu phác, Trần bì, Cam thảo', null, '', null, 'Cốm Bình vị', 'NC14-H07-09', null, 'CON_HANG', null, 1, 5, 5, 5),
('Hoè hoa, Ngưu tất, Đại mạch, Cúc hoa, Lá sen, Đảng sâm nam, Cỏ ngọt, Vỏ đậu xanh', null, '', null, 'Chè hạ áp', 'NC15-H07-09', null, 'CON_HANG', null, 1, 5, 5, 5),
('Bột Angala 500mg (pectic polysacharid chiết xuất từ rễ củ cây đương quy Nhật bản)', null, '', null, 'Somanimm', 'NC30-H12-12', null, 'CON_HANG', null, 1, 5, 5, 5),
('Cao đặc 0,845gam tương ứng (Nhân sâm, Bạch truật, Cam thảo, Đại táo, Bạch linh, Hoài sơn, Cát cánh, Sa nhân), ', null, '', null, 'Cốm trẻ việt', 'NC31-H04-12', null, 'CON_HANG', null, 1, 5, 5, 5),
('Đương quy di thực 1,35 gam', null, '', null, 'Angobin', 'NC32-H08-12', null, 'CON_HANG', null, 1, 6, 6, 6),
('Menthol, Thymol, Camphor, tinh dầu quế, tinh dầu bạc hà, tinh dầu long não, Methyl salicylat', null, '', null, 'Thiên việt hương', 'NC33-H10-12', null, 'CON_HANG', null, 1, 6, 6, 6),
('Thục địa, Hoài sơn, Sơn thù, Kỷ tử, Cam thảo trích, Phụ tử chế, Nhục quế, Đỗ trọng', null, '', null, 'Bổ thận tráng dương', 'NC34-H10-12', null, 'CON_HANG', null, 1, 6, 6, 6),
('Mai mực, Khương hoàng, Hương phụ, Cam thảo, Hoài sơn, Chỉ xác, Mật ong, Cao Belladon', null, '', null, 'Amiprogast', 'NC35-H10-12', null, 'CON_HANG', null, 1, 6, 6, 6),
('Đương quy, Đan sâm, Ngưu tất, Sinh địa, ích mẫu, Xuyên khung, Câu đằng', null, '', null, 'Hoạt huyết ích trí kiện não CM8', 'NC36-H12-12', null, 'CON_HANG', null, 1, 6, 6, 6),
('Bột Sp3 750mg  (tương đương 15 gam cây Ngũ sắc)', null, '', null, 'Agerhinin (gia hạn lần 1)', 'NC37-H05-13', null, 'CON_HANG', null, 1, 6, 6, 6),
('Barisulfat', 'Natri carboxyhnenthylcellulose , Methylparaben , Propyparaben, Nước cất vừa đủ.', 'Hỗn dịch', null, 'Arobarit QH 06', 'NC38-H08-13', null, 'CON_HANG', null, 1, 6, 6, 6),
('Bột Bidentin', null, 'Viên nang', null, 'Bidentin', 'NC39-H10-13', null, 'CON_HANG', null, 1, 6, 6, 6),
('Cao khô Sotinin', null, 'Viên nén bao đường', null, 'Sotinin', 'NC44-H09-14', null, 'CON_HANG', null, 1, 6, 6, 6),
('Cao Đương quy, bột Đương quy, tinh dầu lá Đương quy', null, 'Viên nén bao đường', null, 'Angobin (Gia han lần 1)', 'NC45-H12-14', null, 'CON_HANG', null, 1, 6, 6, 6),
('Felodipin 5 mg', null, 'Viên nén bao phim tác dụng kéo dài', null, 'Felodipin Stada 5 mg', 'GCXK-5-16', null, 'CON_HANG', null, 1, 1, 1, 1),
('Acid tranexamic 1g/10ml', null, 'dung dịch tiêm', null, 'Tranexamic acid 1g <NP>', 'GCXK-8-16', null, 'CON_HANG', null, 1, 6, 6, 6),
('Piracetam 800mg', null, 'Viên nén bao phim', null, 'Piracetam Stada 800 mg', 'GCXK-9-16', null, 'CON_HANG', null, 1, 6, 6, 6),
('Thương truật, Hậu phác, Trần bì, Cam thảo', null, '', null, 'Cốm Bình vị', 'NC14-H07-09', null, 'CON_HANG', null, 1, 6, 6, 6),
('Hoè hoa, Ngưu tất, Đại mạch, Cúc hoa, Lá sen, Đảng sâm nam, Cỏ ngọt, Vỏ đậu xanh', null, '', null, 'Chè hạ áp', 'NC15-H07-09', null, 'CON_HANG', null, 1, 6, 6, 6),
('Bột Angala 500mg', null, '', null, 'Somanimm', 'NC30-H12-12', null, 'CON_HANG', null, 1, 6, 6, 6),
('Cao đặc 0,845gam', null, '', null, 'Cốm trẻ việt', 'NC31-H04-12', null, 'CON_HANG', null, 1, 6, 6, 6),
('Đương quy di thực 1,35 gam', null, '', null, 'Angobin', 'NC32-H08-12', null, 'CON_HANG', null, 1, 6, 6, 6),
('Methoxy polyethylene glycol - epoetin beta', null, 'Dung dịch tiêm', null, 'Micera', 'QLSP-1151-19', null, 'CON_HANG', null, 1, 6, 6, 6),
('Rituximab', null, 'Dung dịch đậm đặc để truyền tĩnh mạch', null, 'Mabthera', 'QLSP-1152-19', null, 'CON_HANG', null, 1, 6, 6, 6),
('Ustekinumab', null, 'Dung dịch tiêm', null, 'Stelara', 'QLSP-1153-19', null, 'CON_HANG', null, 1, 6, 6, 6),
('Thymomodulin', null, 'Viên nang cứng', null, 'Greenpam Hard capsule', 'QLSP-1155-19', null, 'CON_HANG', null, 1, 6, 6, 6),
('Recombinant human erythropoietin', null, 'Dung dịch tiêm', null, 'Epocassa', 'QLSP-H03-1156-19', null, 'CON_HANG', null, 1, 6, 6, 6),
('Recombinant human erythropoietin alffa', null, 'Dung dịch tiêm', null, 'Epocassa', 'QLSP-H03-1157-19', null, 'CON_HANG', null, 1, 6, 6, 6),
('Filgrastim', null, 'Dung dịch tiêm', null, 'Neutrofil 48', 'QLSP-H03-1158-19', null, 'CON_HANG', null, 1, 6, 6, 6),
('Insulin lispro', null, 'Hỗn dịch tiêm', null, 'Humalog Mix25 Kwikpen', 'QLSP-H03-1160-19', null, 'CON_HANG', null, 1, 6, 6, 6),
('Golimumab', null, 'Dung dịch tiêm', null, 'Simponi', 'QLSP-H03-1162-19', null, 'CON_HANG', null, 1, 6, 6, 6),
('Daratumumab', null, 'Dung dịch đậm đặc để pha dung dịch truyền', null, 'Darzalex', 'QLSP-H03-1163-19', null, 'CON_HANG', null, 1, 6, 6, 6),
('Idursulfase', null, 'Hộp 1 lọ 3ml', null, 'Elaprase', 'QLSP-H03-1164-19', null, 'CON_HANG', null, 1, 7, 7, 7),
('Yếu tố đông máu VIII người tái tổ hợp;', null, 'Bột đông khô và dung môi pha dung dịch tiêm', null, 'Advate', 'QLSP-H03-1165-19', null, 'CON_HANG', null, 1, 7, 7, 7),
('Yếu tố đông máu VIII người tái tổ hợp', null, 'Bột đông khô và dung môi pha dung dịch tiêm', null, 'Advate', 'QLSP-H03-1166-19', null, 'CON_HANG', null, 1, 7, 7, 7),
('Yếu tố đông máu VIII người tái tổ hợp (Octocog alfa)', null, 'Bột đông khô và dung môi pha dung dịch tiêm', null, 'Advate', 'QLSP-H03-1167-19', null, 'CON_HANG', null,1, 7, 7, 7),
('Yếu tố đông máu VIII người tái tổ hợp', null, 'Bột đông khô và dung môi pha dung dịch tiêm', null, 'Advate', 'QLSP-H03-1168-19', null, 'CON_HANG', null, 1, 7, 7, 7),
('Immunoglobulin người', null, 'Dung dịch tiêm', null, 'Hizentra', 'QLSP-H03-1169-19', null, 'CON_HANG', null, 1, 7, 7, 7),
('Human immunoglobulin', null, 'Dung dịch tiêm truyền', null, 'Privigen', 'QLSP-H03-1170-19', null, 'CON_HANG', null, 1, 7, 7, 7),
('Yếu tố đông máu số VIII ở người', null, 'Bột đông khô pha tiêm', null, 'Beriate', 'QLSP-H03-1171-19', null, 'CON_HANG', null, 1, 7, 7, 7),
('Adalimumab', null, 'Dung dịch tiêm', null, 'Humira', 'QLSP-H03-1172-19', null, 'CON_HANG', null, 1, 7, 7, 7),
('Adalimumab', null, 'Dung dịch tiêm', null, 'Humira', 'QLSP-H03-1173-19', null, 'CON_HANG', null, 1, 7, 7, 7),
('Trastuzumab', null, 'Bột đông khô pha tiêm', null, 'Hertraz 150', 'QLSP-H03-1174-19', null, 'CON_HANG', null,1, 7, 7, 7),
('Trastuzumab', null, 'Bột đông khô pha tiêm', null, 'Hertraz 440', 'QLSP-H03-1175-19', null, 'CON_HANG', null,1, 7, 7, 7),
('Trastuzumab', null, 'Bột đông khô pha truyền tĩnh mạch', null, 'Herticad 150mg', 'QLSP-H03-1176-19', null, 'CON_HANG', null, 1, 7, 7, 7),
('Huyết thanh tuýp 1 polysaccharid phế cầu khuẩn;', null, 'Hỗn dịch tiêm', null, 'Prevenar 13', 'QLVX-H03-1142-19', null, 'CON_HANG', null, 1, 2, 1, 4),
('Huyết thanh tuýp 1 polysaccharid phế cầu khuẩn;', null, 'Hỗn dịch tiêm', null, 'Prevenar 13', 'QLVX-H03-1143-19', null, 'CON_HANG', null, 1, 2, 1, 4),
('Tenofovir disoproxil fumarat', null, 'Viên nén bao phim', null, 'Unicavir', 'QLĐB-341-12', null, 'CON_HANG', null, 1, 3, 1, 5),
('Adefovir dipivoxil 10mg', null, 'Viên nén bao phim', null, 'Liverdox', 'QLĐB-342-12', null, 'CON_HANG', null, 1, 3, 1, 5),
('Tenofovir disoproxil fumarat', null, 'viên nén dài bao phim', null, 'Hepatymo', 'QLĐB-343-12', null, 'CON_HANG', null, 1, 3, 1, 5),
('Promethazin hydroclorid, Codein phosphat, Phenylephrin', 'Lactose, tinh bột sắn, PVP', 'Viên nén bao phim', null, 'Tosren', 'QLĐB-344-12', null, 'CON_HANG', null, 1, 3, 2, 6),
('Natri clorid, Natri citrat, Kali clorid, Glucose, Kẽm gluconat', null, 'Thuốc bột uống', null, 'Oremute 10', 'QLĐB-345-12', null, 'CON_HANG', null, 1, 4, 2, 7),
('Natri clorid, Natri citrat, Kali clorid, Glucose, Kẽm gluconat', null, 'Thuốc bột uống', null, 'Oremute 20', 'QLĐB-346-12', null, 'CON_HANG', null, 1, 4, 2, 7),
('Natri clorid, Natri citrat, Kali clorid, Glucose, Kẽm gluconat', null, 'Thuốc bột uống', null, 'Oremute 5', 'QLĐB-347-12', null, 'CON_HANG', null, 1, 4, 2, 7),
('Docetaxel', null, 'dung dịch thuốc tiêm đậm đặc pha truyền tĩnh mạch', null, 'Bestdocel 80', 'QLĐB-348-12', null, 'CON_HANG', null, 1, 4, 2, 8),
('Paclitaxel', null, 'Thuốc tiêm pha truyền tĩnh mạch', null, 'Canpaxel 30', 'QLĐB-349-12', null, 'CON_HANG', null, 1, 4, 2, 8),
('Capecitabin', null, 'Viên nén bao phim', null, 'Relotabin', 'QLĐB-350-12', null, 'CON_HANG', null, 1, 4, 3, 9),
('Tenofovir disoproxil fumarat', 'Lactose monohydrat, tinh bột pregelatinized, croscarmelose natri', 'viên nén dài bao phim', null, 'SaVi Tenofovir 150', 'QLĐB-351-12', null, 'CON_HANG', null, 1, 3, 1, 8),
('Tenofovir disoproxil fumarat', null, 'viên nén dài bao phim', null, 'Mibeproxil', 'QLĐB-352-12', null, 'CON_HANG', null, 1, 3, 1, 5),
('Paracetamol; Methocarbamol', 'Lactose, Microcrystallin cellulose, Crosscarmellose, Povidone', 'Viên nén bao phim', null, 'Parocontin', 'QLĐB-353-12', null, 'CON_HANG', null, 1, 4, 4, 8),
('Mifepriston', 'Eragel, Lactose monohydrat,', 'Viên nén', null, 'Mifenan', 'QLĐB-354-12', null, 'CON_HANG', null, 1, 4, 5, 10),
('Mifepriston', 'lactose monohydrat, tinh bột ngô, PVP K30', 'Viên nén', null, 'Mifepristone 10', 'QLĐB-355-12', null, 'CON_HANG', null, 1, 4, 5, 8)
;

-- Supplier 1: Products 1 to 30
INSERT INTO public.product_supplier (product_id, supplier_id)
VALUES
(1, 1), (2, 1), (3, 1), (4, 1), (5, 1),
(6, 1), (7, 1), (8, 1), (9, 1), (10, 1),
(11, 1), (12, 1), (13, 1), (14, 1), (15, 1),
(16, 1), (17, 1), (18, 1), (19, 1), (20, 1),
(21, 1), (22, 1), (23, 1), (24, 1), (25, 1),
(26, 1), (27, 1), (28, 1), (29, 1), (30, 1),
(31, 2), (32, 2), (33, 2), (34, 2), (35, 2),
(36, 2), (37, 2), (38, 2), (39, 2), (40, 2),
(41, 2), (42, 2), (43, 2), (44, 2), (45, 2),
(46, 2), (47, 2), (48, 2), (49, 2), (50, 2),
(51, 2), (52, 2), (53, 2), (54, 2), (55, 2),
(56, 2), (57, 2), (58, 2), (59, 2), (60, 2),
(61, 3), (62, 3), (63, 3), (64, 3), (65, 3),
(66, 3), (67, 3), (68, 3), (69, 3), (70, 3),
(71, 3), (72, 3), (73, 3), (74, 3), (75, 3),
(76, 3), (77, 3), (78, 3), (79, 3), (80, 3),
(81, 3), (82, 3), (83, 3), (84, 3), (85, 3),
(86, 3), (87, 3), (88, 3), (89, 3), (90, 3),
(91, 4), (92, 4), (93, 4), (94, 4), (95, 4),
(96, 4), (97, 4), (98, 4), (99, 4), (100, 4),
(101, 4), (102, 4), (103, 4), (104, 4), (105, 4),
(106, 4), (107, 4), (108, 4), (109, 4), (110, 4),
(111, 4), (112, 4), (113, 4), (114, 4), (115, 4),
(116, 4), (117, 4), (118, 4), (119, 4), (120, 4),
(121, 5), (122, 5), (123, 5), (124, 5), (125, 5),
(126, 5), (127, 5), (128, 5), (129, 5), (130, 5),
(131, 5), (132, 5), (133, 5), (134, 5), (135, 5),
(136, 5), (137, 5), (138, 5), (139, 5), (140, 5),
(141, 5), (142, 5), (143, 5), (144, 5), (145, 5),
(146, 5), (147, 5), (148, 5), (149, 5), (150, 5),
(151, 6), (152, 6), (153, 6), (154, 6), (155, 6),
(156, 6), (157, 6), (158, 6), (159, 6), (160, 6),
(161, 6), (162, 6), (163, 6), (164, 6), (165, 6),
(166, 6), (167, 6), (168, 6), (169, 6),
(170, 7), (171, 7), (172, 7), (173, 7), (174, 7),
(175, 7), (176, 7), (177, 7), (178, 7), (179, 7),
(180, 7), (181, 7), (182, 7), (183, 7), (184, 7),
(185, 7), (186, 7), (187, 7);

-- Chèn dữ liệu cho Chi nhánh 1
DO $$
BEGIN
    FOR i IN 1..180 LOOP
        INSERT INTO public.branch_product (max_quantity, min_quantity, quantity, branch_id, product_id, location_id, status)
        VALUES (1000, 10, NULL, 1, i, NULL, 1);
    END LOOP;
END $$;

-- Chèn dữ liệu cho Chi nhánh 2
DO $$
BEGIN
    FOR i IN 1..180 LOOP
        INSERT INTO public.branch_product (max_quantity, min_quantity, quantity, branch_id, product_id, location_id, status)
        VALUES (1000, 10, NULL, 2, i, NULL, 1);
    END LOOP;
END $$;

-- Chèn dữ liệu cho Chi nhánh 3
DO $$
BEGIN
    FOR i IN 1..180 LOOP
        INSERT INTO public.branch_product (max_quantity, min_quantity, quantity, branch_id, product_id, location_id, status)
        VALUES (1000, 10, NULL, 3, i, NULL, 1);
    END LOOP;
END $$;

-- Chèn dữ liệu cho Chi nhánh 4
DO $$
BEGIN
    FOR i IN 1..180 LOOP
        INSERT INTO public.branch_product (max_quantity, min_quantity, quantity, branch_id, product_id, location_id, status)
        VALUES (1000, 10, NULL, 4, i, NULL, 1);
    END LOOP;
END $$;

UPDATE public.product
SET 
    inbound_price = FLOOR((random() * (50000 - 10000) + 10000) / 1000) * 1000;

UPDATE public.product
SET 
    sell_price = 
        CASE 
            WHEN inbound_price + 20000 <= 100000 THEN inbound_price + 20000
            ELSE 100000
        END;