# App custom configs
hrm-config:
  jwt:
    secret: soUicqC3yUtp0lq1st57RVt5g36048StY291PwPIMyI=
    expiration: 86400000
  minio:
    endpoint: http://localhost:9000
    username: lpdev
    password: Abcd1234
    bucket: dsd
    access-key: hum4ag5K2Lq5dzF3T3nc
    secret-key: pVSiNZ11N7hnnMSJPwNHT7jMMkKYTJiJhqAW0Ww8
  mail:
    subject: "OTP for authentication in GoldenView"
    content: "Do not send this OTP to anyone for security protection. Your otp is: "
  s3:
    key: ${DO_S3_KEY}
    secret: ${DO_S3_SECRET}
    endpoint: ${DO_S3_ENDPOINT}
    region: ${DO_S3_REGION}
    bucket: ${DO_S3_BUCKET}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tiendat288966@gmail.com
    password: hfqcaubtteeyrmef
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hrm
    username: lpdev
    password: Abcd1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: false
server:
  servlet:
    session:
      timeout: 3600m
