spring:
  jackson:
    time-zone:
      UTC
    date-format:
      "yyyy-MM-dd'T'HH:mm:ss.SSSX"
  servlet:
    multipart:
      enabled:
        true
      max-file-size:
        256MB
      max-request-size:
        256MB

springdoc:
  api-docs:
    path: /swagger/v3/api-docs
  swagger-ui:
    path: /swagger/index.html