# App custom configs
hrm-config:
  jwt:
    secret: soUicqC3yUtp0lq1st57RVt5g36048StY291PwPIMyI=
    expiration: 86400000
  minio:
    endpoint: http://aninfosys.asia:9001
    username: lpdev
    password: Abcd1234
    bucket: dsd
    access-key: Uh5YevGK2IbAjJFJrU7o
    secret-key: M7io1j7dvmV6eUHUXwkddvoKQKwAr8IEzmpRZKhQ
  mail:
    subject: "OTP for authentication in GoldenView"
    content: "Do not send this OTP to anyone for security protection. Your otp is: "

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tiendat288966@gmail.com
    password: hfqcaubtteeyrmef
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://aninfosys.asia:5433/dsd
    username: lpdev
    password: Abcd1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: false