server:
  # fix swagger unable to call API due to http and https
  forward-headers-strategy: framework
  port: 8081
  servlet:
    context-path: /dsd

spring:
  profiles:
    active:
      - "@spring.profiles.active@"
    include:
      - "common"

  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: tiendat288966@gmail.com
    password: hfqcaubtteeyrmef
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

