version: "3.8"
services:
  postgres:
    image: postgres:16.0
    container_name: hrm_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lpdev
      POSTGRES_PASSWORD: Abcd1234
      POSTGRES_DB: hrm
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1-standalone
    container_name: hrm_adminer
    restart: unless-stopped
    ports:
      - "8079:8080"